name = 'cf-worker-verified-email-router'
main = "src/index.ts"
compatibility_date = "2026-09-09"
keep_vars = true

[[send_email]]
name = "EMAIL"

[[email]]
name = "EMAIL_HANDLER"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true
